### ISSUE TITLE
Since uninstalling this .dds format won't open in paint.net

### ISSUE THREAD

**Issue by Tycoonspaceman** [dtzxporter/FileTypeDDS#1]
was looking for something to open .bc5 format which this dies found that i could not save as .dds so uninstalled by removing FileTypeDDS64.dll from the Filetypes, but paint.net responds with an error, I have tried uninstalling and reinstalling paint.net itself but that alas also did not fix the issue. 
![error](https://user-images.githubusercontent.com/37255483/37248432-4e28529a-24ca-11e8-8957-b77eb6742fdc.png)

**Comment by dtzxporter** [comment]
You have to repair your install, since, this patches the PaintDotNet exe to enable patches for the program to load a custom dds handler.
