### ISSUE TITLE
Unable to open DDS file after removing FileTypeDDS64.dll

### ISSUE THREAD

**Issue by phuccom000** [dtzxporter/FileTypeDDS#2]
I was unable to open DDS file after removing the file
As I installed the plugin, the ability to export the file as dds also disappeared.
Please help
I was unable to repair the file too.

**Comment by dtzxporter** [comment]
Your Paint.NET exe was patched to make this happen, locate the .bak version in the installation folder and replace the existing one with it. 

Then, run:
```
%windir%\Microsoft.NET\Framework64\v4.0.30319\ngen.exe uninstall C:\path\to\paint.net\Paintdotnet.exe
``` 
in a command prompt (OR just re-run the paint.net installer)

**Comment by dtzxporter** [comment]
Also @phuccom000 Release v1.0.0 has save support and an uninstaller. https://github.com/dtzxporter/FileTypeDDS/releases/tag/v1.0.0
